apiVersion: v1
kind: Secret
metadata:
  name: vmetal-dhcp-network-template
  namespace: vcluster-platform
  labels:
    vcluster.com/user-data-template-type: network-data
type: Opaque
stringData:
  data: |
    {
      "links": [
        {
          "id": "provisioning-nic",
          "type": "phy",
          "ethernet_mac_address": "{{ index .Values.BareMetalHost "spec" "bootMACAddress" }}"
        }
      ],
      "networks": [
        {
          "id": "provisioning-net",
          "link": "provisioning-nic",
          "type": "ipv4_dhcp"
        }
      ],
      "services": [
        {
          "type": "dns",
          "address": "172.22.0.1"
        }
      ],
      "meta": {
        "host": "{{ index .Values.BareMetalHost "metadata" "name" }}",
        "claim": "{{ .Values.NodeClaim.Name }}",
        "project": "{{ .Values.Project }}",
        "network": "br-provision",
        "gateway": "172.22.0.1"
      }
    }
